/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Organization */
        post: operations["create_organization_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_organizations__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Organization */
        patch: operations["update_organization_organizations__org_id__patch"];
        trace?: never;
    };
    "/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_organizations__org_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_organizations__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_organizations__org_id__members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_organizations__org_id__members__member_id__patch"];
        trace?: never;
    };
    "/organizations/{org_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_organizations__org_id__audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_organizations__org_id__workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_organizations__org_id__workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_organizations__org_id__workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Workspace */
        patch: operations["update_workspace_organizations__org_id__workspaces__workspace_id__patch"];
        trace?: never;
    };
    "/organizations/{org_id}/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspace Members */
        get: operations["list_workspace_members_organizations__org_id__workspaces__workspace_id__members_get"];
        put?: never;
        /** Add Workspace Member */
        post: operations["add_workspace_member_organizations__org_id__workspaces__workspace_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}/workspaces/{workspace_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Workspace Member */
        delete: operations["remove_workspace_member_organizations__org_id__workspaces__workspace_id__members__member_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deadlines/notice-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notice Preview */
        post: operations["notice_preview_deadlines_notice_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Workspace Id */
            workspace_id: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** CalendarIn */
        CalendarIn: {
            /** Country */
            country?: string | null;
            /** Subdivision */
            subdivision?: string | null;
            /**
             * Weekend
             * @description 0=Monday … 6=Sunday
             * @default [
             *       5,
             *       6
             *     ]
             */
            weekend?: number[];
        };
        /**
         * DayBasis
         * @enum {string}
         */
        DayBasis: "calendar" | "business";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            /** Organizations */
            organizations: components["schemas"]["MyOrganization"][];
        };
        /** MyOrganization */
        MyOrganization: {
            organization: components["schemas"]["OrganizationOut"];
            role: components["schemas"]["OrgRole"];
        };
        /** NoticePreviewIn */
        NoticePreviewIn: {
            /**
             * Effective Date
             * Format: date
             */
            effective_date: string;
            initial_term: components["schemas"]["PeriodIn"];
            renewal_term?: components["schemas"]["PeriodIn"] | null;
            notice_period: components["schemas"]["PeriodIn"];
            delivery_period?: components["schemas"]["PeriodIn"] | null;
            /**
             * @default {
             *       "weekend": [
             *         5,
             *         6
             *       ]
             *     }
             */
            calendar?: components["schemas"]["CalendarIn"];
            /** @default preceding */
            roll?: components["schemas"]["Roll"];
            /** As Of */
            as_of?: string | null;
        };
        /** NoticePreviewOut */
        NoticePreviewOut: {
            term: components["schemas"]["TermOut"];
            /**
             * Notice Deadline
             * Format: date
             */
            notice_deadline: string;
            /** Days Left */
            days_left: number;
            /** Derivation */
            derivation: string[];
        };
        /** OrgMemberCreate */
        OrgMemberCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default member */
            role?: components["schemas"]["OrgRole"];
        };
        /** OrgMemberOut */
        OrgMemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            user: components["schemas"]["UserOut"];
            role: components["schemas"]["OrgRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrgMemberUpdate */
        OrgMemberUpdate: {
            role: components["schemas"]["OrgRole"];
        };
        /**
         * OrgRole
         * @enum {string}
         */
        OrgRole: "owner" | "admin" | "member";
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            kind: components["schemas"]["OrganizationKind"];
            /**
             * Default Timezone
             * @default UTC
             */
            default_timezone?: string;
            /** Default Country */
            default_country?: string | null;
        };
        /**
         * OrganizationKind
         * @enum {string}
         */
        OrganizationKind: "company" | "holding" | "law_firm";
        /** OrganizationOut */
        OrganizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["OrganizationKind"];
            /** Default Timezone */
            default_timezone: string;
            /** Default Country */
            default_country: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrganizationUpdate */
        OrganizationUpdate: {
            /** Name */
            name?: string | null;
            /** Default Timezone */
            default_timezone?: string | null;
            /** Default Country */
            default_country?: string | null;
        };
        /** PeriodIn */
        PeriodIn: {
            /** Amount */
            amount: number;
            unit: components["schemas"]["Unit"];
            /** @default calendar */
            basis?: components["schemas"]["DayBasis"];
        };
        /**
         * Roll
         * @description How to adjust a date that falls on a non-business day.
         * @enum {string}
         */
        Roll: "none" | "preceding" | "following";
        /** TermOut */
        TermOut: {
            /** Number */
            number: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "days" | "weeks" | "months" | "years";
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
            kind: components["schemas"]["WorkspaceKind"];
            /** Parent Workspace Id */
            parent_workspace_id?: string | null;
            /** Country */
            country?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * WorkspaceKind
         * @enum {string}
         */
        WorkspaceKind: "client" | "entity" | "department";
        /** WorkspaceMemberCreate */
        WorkspaceMemberCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default viewer */
            role?: components["schemas"]["WorkspaceRole"];
        };
        /** WorkspaceMemberOut */
        WorkspaceMemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            user: components["schemas"]["UserOut"];
            role: components["schemas"]["WorkspaceRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Parent Workspace Id */
            parent_workspace_id: string | null;
            /** Name */
            name: string;
            kind: components["schemas"]["WorkspaceKind"];
            /** Country */
            country: string | null;
            /** Timezone */
            timezone: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WorkspaceRole
         * @enum {string}
         */
        WorkspaceRole: "admin" | "editor" | "viewer";
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Name */
            name?: string | null;
            /** Country */
            country?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** WorkspaceWithRole */
        WorkspaceWithRole: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Parent Workspace Id */
            parent_workspace_id: string | null;
            /** Name */
            name: string;
            kind: components["schemas"]["WorkspaceKind"];
            /** Country */
            country: string | null;
            /** Timezone */
            timezone: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            my_role: components["schemas"]["WorkspaceRole"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_organizations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_organizations__org_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_organizations__org_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_organizations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_organizations__org_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_organizations__org_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                member_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_organizations__org_id__members__member_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                member_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_organizations__org_id__audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_organizations__org_id__workspaces_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceWithRole"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_organizations__org_id__workspaces_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_organizations__org_id__workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                workspace_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceWithRole"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_organizations__org_id__workspaces__workspace_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                workspace_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspace_members_organizations__org_id__workspaces__workspace_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                workspace_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_workspace_member_organizations__org_id__workspaces__workspace_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                workspace_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_workspace_member_organizations__org_id__workspaces__workspace_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path: {
                workspace_id: string;
                member_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notice_preview_deadlines_notice_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-user-email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticePreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
