"""amendments

Revision ID: 6bdd68c84ea5
Revises: b70b8cf47f59
Create Date: 2026-10-07 19:23:48.066127

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bdd68c84ea5"
down_revision: str | Sequence[str] | None = "b70b8cf47f59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ("amendments", "amendment_changes")
CURRENT_ORG = "NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amendments",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amendments_contract_id"), "amendments", ["contract_id"], unique=False)
    op.create_index(
        op.f("ix_amendments_organization_id"), "amendments", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_amendments_workspace_id"), "amendments", ["workspace_id"], unique=False
    )
    op.create_table(
        "amendment_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("amendment_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("field", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["amendment_id"], ["amendments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_amendment_changes_amendment_id"),
        "amendment_changes",
        ["amendment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_amendment_changes_organization_id"),
        "amendment_changes",
        ["organization_id"],
        unique=False,
    )
    op.add_column("documents", sa.Column("amendment_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_documents_amendment_id"), "documents", ["amendment_id"], unique=False)
    op.create_foreign_key(
        "documents_amendment_id_fkey",
        "documents",
        "amendments",
        ["amendment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (organization_id = {CURRENT_ORG}) "
            f"WITH CHECK (organization_id = {CURRENT_ORG})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("documents_amendment_id_fkey", "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_amendment_id"), table_name="documents")
    op.drop_column("documents", "amendment_id")
    op.drop_index(op.f("ix_amendment_changes_organization_id"), table_name="amendment_changes")
    op.drop_index(op.f("ix_amendment_changes_amendment_id"), table_name="amendment_changes")
    op.drop_table("amendment_changes")
    op.drop_index(op.f("ix_amendments_workspace_id"), table_name="amendments")
    op.drop_index(op.f("ix_amendments_organization_id"), table_name="amendments")
    op.drop_index(op.f("ix_amendments_contract_id"), table_name="amendments")
    op.drop_table("amendments")
    # ### end Alembic commands ###
