"""deadline decisions

Revision ID: ee865385db46
Revises: 6cb4b7702042
Create Date: 2026-10-07 17:29:38.598060

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee865385db46"
down_revision: str | Sequence[str] | None = "6cb4b7702042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DECISION = postgresql.ENUM(
    "renew",
    "renegotiate",
    "terminate",
    "let_expire",
    "exercise_option",
    "no_action",
    name="deadline_decision",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    DECISION.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "deadlines",
        sa.Column(
            "decision", postgresql.ENUM(name="deadline_decision", create_type=False), nullable=True
        ),
    )
    op.add_column("deadlines", sa.Column("decision_note", sa.Text(), nullable=True))
    op.add_column("deadlines", sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("deadlines", sa.Column("decided_by_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "deadlines_decided_by_id_fkey",
        "deadlines",
        "users",
        ["decided_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("deadlines_decided_by_id_fkey", "deadlines", type_="foreignkey")
    op.drop_column("deadlines", "decided_by_id")
    op.drop_column("deadlines", "decided_at")
    op.drop_column("deadlines", "decision_note")
    op.drop_column("deadlines", "decision")
    DECISION.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
