"""contracts documents and deadlines

Revision ID: da86aef093b7
Revises: 6af33eb13141
Create Date: 2026-10-07 08:48:37.379467

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da86aef093b7"
down_revision: str | Sequence[str] | None = "6af33eb13141"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUMS = {
    "contract_status": (
        "processing",
        "needs_review",
        "active",
        "expired",
        "terminated",
    ),
    "period_unit": (
        "days",
        "weeks",
        "months",
        "years",
    ),
    "date_rule_type": (
        "non_renewal_notice",
        "termination_notice",
        "option_exercise",
        "price_review",
        "warranty_end",
        "insurance_expiry",
        "guarantee_expiry",
        "lock_in_end",
        "other",
    ),
    "date_anchor": (
        "fixed_date",
        "effective_date",
        "term_start",
        "term_end",
    ),
    "day_basis": (
        "calendar",
        "business",
    ),
    "offset_direction": (
        "before",
        "after",
    ),
    "review_status": (
        "ai_suggested",
        "confirmed",
        "edited",
        "rejected",
    ),
    "document_status": (
        "uploaded",
        "processing",
        "ready",
        "failed",
    ),
    "payment_direction": (
        "receivable",
        "payable",
        "unknown",
    ),
    "payment_frequency": (
        "one_off",
        "monthly",
        "quarterly",
        "semi_annual",
        "annual",
        "other",
    ),
    "deadline_kind": (
        "term_end",
        "notice",
        "option",
        "price_review",
        "payment",
        "other",
    ),
    "deadline_status": (
        "open",
        "done",
        "dismissed",
    ),
}

TENANT_TABLES = (
    "contracts",
    "documents",
    "clauses",
    "extraction_runs",
    "date_rules",
    "payment_terms",
    "deadlines",
)
CURRENT_ORG = "NULLIF(current_setting('app.org_id', true), '')::uuid"


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for name, values in ENUMS.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "processing",
                "needs_review",
                "active",
                "expired",
                "terminated",
                name="contract_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("contract_type", sa.String(length=100), nullable=True),
        sa.Column("counterparty_name", sa.String(length=500), nullable=True),
        sa.Column("parties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("initial_term_amount", sa.Integer(), nullable=True),
        sa.Column(
            "initial_term_unit",
            postgresql.ENUM(
                "days", "weeks", "months", "years", name="period_unit", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("auto_renews", sa.Boolean(), nullable=True),
        sa.Column("renewal_term_amount", sa.Integer(), nullable=True),
        sa.Column(
            "renewal_term_unit",
            postgresql.ENUM(
                "days", "weeks", "months", "years", name="period_unit", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("governing_law", sa.String(length=200), nullable=True),
        sa.Column("holiday_country", sa.String(length=2), nullable=True),
        sa.Column("holiday_subdivision", sa.String(length=10), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("contract_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("notice_details", sa.Text(), nullable=True),
        sa.Column("field_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contracts_organization_id"), "contracts", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_contracts_workspace_id"), "contracts", ["workspace_id"], unique=False)
    op.create_table(
        "date_rules",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rule_type",
            postgresql.ENUM(
                "non_renewal_notice",
                "termination_notice",
                "option_exercise",
                "price_review",
                "warranty_end",
                "insurance_expiry",
                "guarantee_expiry",
                "lock_in_end",
                "other",
                name="date_rule_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column(
            "anchor",
            postgresql.ENUM(
                "fixed_date",
                "effective_date",
                "term_start",
                "term_end",
                name="date_anchor",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("fixed_date", sa.Date(), nullable=True),
        sa.Column("offset_amount", sa.Integer(), nullable=True),
        sa.Column(
            "offset_unit",
            postgresql.ENUM(
                "days", "weeks", "months", "years", name="period_unit", create_type=False
            ),
            nullable=True,
        ),
        sa.Column(
            "offset_basis",
            postgresql.ENUM("calendar", "business", name="day_basis", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("before", "after", name="offset_direction", create_type=False),
            nullable=False,
        ),
        sa.Column("delivery_amount", sa.Integer(), nullable=True),
        sa.Column(
            "delivery_basis",
            postgresql.ENUM("calendar", "business", name="day_basis", create_type=False),
            nullable=False,
        ),
        sa.Column("compute_error", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_clause_refs", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "ai_suggested",
                "confirmed",
                "edited",
                "rejected",
                name="review_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_date_rules_contract_id"), "date_rules", ["contract_id"], unique=False)
    op.create_index(
        op.f("ix_date_rules_organization_id"), "date_rules", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_date_rules_workspace_id"), "date_rules", ["workspace_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "uploaded",
                "processing",
                "ready",
                "failed",
                name="document_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("text_source", sa.String(length=20), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_contract_id"), "documents", ["contract_id"], unique=False)
    op.create_index(
        op.f("ix_documents_organization_id"), "documents", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_documents_sha256"), "documents", ["sha256"], unique=False)
    op.create_index(op.f("ix_documents_workspace_id"), "documents", ["workspace_id"], unique=False)
    op.create_table(
        "payment_terms",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "direction",
            postgresql.ENUM(
                "receivable", "payable", "unknown", name="payment_direction", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "frequency",
            postgresql.ENUM(
                "one_off",
                "monthly",
                "quarterly",
                "semi_annual",
                "annual",
                "other",
                name="payment_frequency",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("first_due_date", sa.Date(), nullable=True),
        sa.Column("payment_days", sa.Integer(), nullable=True),
        sa.Column("escalation", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_clause_refs", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "ai_suggested",
                "confirmed",
                "edited",
                "rejected",
                name="review_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_terms_contract_id"), "payment_terms", ["contract_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_terms_organization_id"), "payment_terms", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_terms_workspace_id"), "payment_terms", ["workspace_id"], unique=False
    )
    op.create_table(
        "clauses",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ref", sa.String(length=20), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=True),
        sa.Column("heading", sa.String(length=500), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ref"),
    )
    op.create_index(op.f("ix_clauses_document_id"), "clauses", ["document_id"], unique=False)
    op.create_index(
        op.f("ix_clauses_organization_id"), "clauses", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_clauses_workspace_id"), "clauses", ["workspace_id"], unique=False)
    op.create_table(
        "deadlines",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("date_rule_id", sa.Uuid(), nullable=True),
        sa.Column("payment_term_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "term_end",
                "notice",
                "option",
                "price_review",
                "payment",
                "other",
                name="deadline_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("derivation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("open", "done", "dismissed", name="deadline_status", create_type=False),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["date_rule_id"], ["date_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_term_id"], ["payment_terms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deadlines_contract_id"), "deadlines", ["contract_id"], unique=False)
    op.create_index(op.f("ix_deadlines_due_date"), "deadlines", ["due_date"], unique=False)
    op.create_index(
        op.f("ix_deadlines_organization_id"), "deadlines", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_deadlines_workspace_id"), "deadlines", ["workspace_id"], unique=False)
    op.create_table(
        "extraction_runs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_runs_document_id"), "extraction_runs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_extraction_runs_organization_id"),
        "extraction_runs",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (organization_id = {CURRENT_ORG}) "
            f"WITH CHECK (organization_id = {CURRENT_ORG})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extraction_runs_organization_id"), table_name="extraction_runs")
    op.drop_index(op.f("ix_extraction_runs_document_id"), table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index(op.f("ix_deadlines_workspace_id"), table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_organization_id"), table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_due_date"), table_name="deadlines")
    op.drop_index(op.f("ix_deadlines_contract_id"), table_name="deadlines")
    op.drop_table("deadlines")
    op.drop_index(op.f("ix_clauses_workspace_id"), table_name="clauses")
    op.drop_index(op.f("ix_clauses_organization_id"), table_name="clauses")
    op.drop_index(op.f("ix_clauses_document_id"), table_name="clauses")
    op.drop_table("clauses")
    op.drop_index(op.f("ix_payment_terms_workspace_id"), table_name="payment_terms")
    op.drop_index(op.f("ix_payment_terms_organization_id"), table_name="payment_terms")
    op.drop_index(op.f("ix_payment_terms_contract_id"), table_name="payment_terms")
    op.drop_table("payment_terms")
    op.drop_index(op.f("ix_documents_workspace_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_sha256"), table_name="documents")
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_contract_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_date_rules_workspace_id"), table_name="date_rules")
    op.drop_index(op.f("ix_date_rules_organization_id"), table_name="date_rules")
    op.drop_index(op.f("ix_date_rules_contract_id"), table_name="date_rules")
    op.drop_table("date_rules")
    op.drop_index(op.f("ix_contracts_workspace_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_organization_id"), table_name="contracts")
    op.drop_table("contracts")
    # ### end Alembic commands ###
    for name in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {name}")
